allowBuilds:
  esbuild: true
enableGlobalVirtualStore: true
registries:
  default: https://registry.npmjs.org/
  "@j4k": https://code.j4k.dev/api/packages/j4k/npm/
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - "@j4k/*"
